package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WebService service = new WebService();
 * WebServiceSoap portType = service.getWebServiceSoap();
 * portType.getUserData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WebService", targetNamespace = "YuanYT.RemotingCall", wsdlLocation = "http://10.10.10.184/rfamis/remotingcall/WebService.asmx?wsdl")
public class WebService extends Service {

	private final static URL WEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(webservice.WebService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webservice.WebService.class.getResource(".");
			url = new URL(baseUrl,
					"http://10.10.10.184/rfamis/remotingcall/WebService.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.10.184/rfamis/remotingcall/WebService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICE_WSDL_LOCATION = url;
	}

	public WebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebService() {
		super(WEBSERVICE_WSDL_LOCATION, new QName("YuanYT.RemotingCall",
				"WebService"));
	}

	/**
	 * 
	 * @return returns WebServiceSoap
	 */
	@WebEndpoint(name = "WebServiceSoap")
	public WebServiceSoap getWebServiceSoap() {
		return super.getPort(
				new QName("YuanYT.RemotingCall", "WebServiceSoap"),
				WebServiceSoap.class);
	}

	/**
	 * 
	 * @return returns WebServiceSoap
	 */
	@WebEndpoint(name = "WebServiceSoap12")
	public WebServiceSoap getWebServiceSoap12() {
		return super.getPort(new QName("YuanYT.RemotingCall",
				"WebServiceSoap12"), WebServiceSoap.class);
	}
	
	public static void main(String args[]){
		WebService ws = new WebService();
		String result = ws.getWebServiceSoap12().getEAIWebDataQMYSforJava("单位余额表",
				"{'CompanyCode':'2000000000','AppCode':'GQ','UserCode':'yyt'}",
				"{'单位':['2HCT00000K','2HCT01400K'],'单位名称':['贺州市建设开发公司','贺州市物业公司'],'单位排序':[1,2]}",
				"{'科目级次':2,'年份':2017,'起始月份':1,'科目':['1001'],'结束月份':3,'是否包含未记帐凭证':true}");
		System.out.println(result);
	}
	

}
